server:
  port: 18080

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
